### ISSUE TITLE
Not working with Fritz!OS 7.25

### ISSUE THREAD

**Issue by mh-g** [schlomo/fritzbox-internet-ticket#2]
I get the following error message on my Fritz!Box 7530 with Fritz!OS 7.25:

```
python fritzbox-get-internet-tickets.py
ERROR: could not get sid, response was:
<?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>b7373f49</Challenge><BlockTime>128</BlockTime><Rights></Rights><Users><User last="1">fritz0724</User></Users></SessionInfo>

ERROR: could not get sid
```

**Comment by mh-g** [comment]
Two issues: 

First, one has to supply a user name, even if only one user is defined in the Fritz!Box. See https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/Recommendations%20for%20user%20guidance%20for%20logging%20into%20a%20FRITZBox_v1.1_EN.pdf for details. (Obtain the name from System/ Fritz!Box-Benutzer.)

Second, the structure of the output has changed. I had to replace the regular expression in line 65 with:

        tickets = re.findall(r'<td class=\"\" id=\"Ticket-\d*\">(\d+)</td>', response.text)

Then all is fine again.

**Comment by jforge** [comment]
Still true for Fritz!OS 7.29, thanks.
